dist: trusty
sudo: required
addons:
    chrome: stable # have Travis install Chrome stable.
cache:
    yarn: true
    directories:
        - node_modules

language: node_js
node_js:
    - 12.8.1

before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
    - export PATH="$HOME/.yarn/bin:$PATH"

install:
    - yarn

script:
    - yarn test
