language: node_js
node_js:
    - "12.8.1"
dist: trusty # needs Ubuntu Trusty
# Note: if you switch to sudo: false, you'll need to launch Chrome with --no-sandbox.
# See https://github.com/travis-ci/travis-ci/issues/8836
sudo: required
addons:
    chrome: stable # have Travis install Chrome stable.
cache:
    yarn: true
    directories:
        - node_modules
before_install:
    # if "install" is overridden
    # Repo for Yarn
    - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
    - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq yarn=1.21.1-1
install:
    - yarn
script:
    - yarn test
